# -*- org-export-babel-evaluate: nil -*-
# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+title: Paper for ERAD 2020
#+author: Henrique Silva

#+startup: overview indent
#+language: pt-br
#+options: H:3 creator:nil timestamp:nil skip:nil toc:nil num:t ^:nil ~:~
#+options: author:nil title:nil date:nil
#+tags: noexport(n) deprecated(d) ignore(i)
#+export_select_tags: export
#+export_exclude_tags: noexport

#+latex_class: article
#+latex_class_options: [12pt]
#+latex_header: \usepackage{sbc-template}
#+latex_header: \usepackage[brazil]{babel}
#+latex_header: \usepackage[utf8]{inputenc}
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \usepackage{graphicx}
#+latex_header: \usepackage[caption=false]{subfig}
#+latex_header: \usepackage{booktabs}
#+latex_header: \usepackage{hyphenat}
#+latex_header: \hyphenation{e-la-bo-ra-ção re-pre-sen-tar}

# You need at least Org 9 and Emacs 24 to make this work.
# If you do, just type make (thanks Luka Stanisic for this).

#+begin_export latex
\author{
   Henrique Corrêa Pereira da Silva\and%\inst{1},
   Marcelo Cogo Milletto\and
   Vinicius Garcia Pinto\and \\
   Lucas Mello Schnorr
}

\address{
  Instituto de Informática -- Universidade Federal do Rio Grande do Sul (UFRGS)\\
  Porto Alegre -- RS -- Brasil
  \email{\{hcpsilva,mcmiletto,vgpinto,schnorr\}@inf.ufrgs.br}
}
#+end_export

\maketitle

#+begin_resumo

#+end_resumo

* Introdução, Objetivos e Trabalhos Relacionados

#+begin_comment
- HPC é tri; contexto (paralelismo de tarefas)
  - Vários /runtimes/ capazes de prover esse paralelismo
  - ...
- Identificação do problema!
  - Problema: o desempenho depende do /runtime/ e não mais do programador
    - Qual é melhor /runtime/? Principalmente, porque um é melhor que outro?
  - Trabalhos relacionados
    - Marcelo
    - Outros a partir do trabalho do Marcelo
- Objetivos
  - Comparação do escalonamento
  - Análise de ociosidade
  - Observação de anomalies dependentes do /runtime/
    (Diferenças de tempo de /kernel/ em função do /runtime/)
- Constribuição
- Estrutura do artigo
#+end_comment

* Metodologia de Coleta e Análise de Dados

#+begin_comment
- Visão geral do workflow
  - Figura mostrando o funcionamento (com o texto a explicando)
#+end_comment

Nessa seção versaremos sobre a metodologia experimental desse trabalho, assim
como o ferramental de /software/ utilizado para a análise dos dados
coletados. Além disso, abordaremos o /workflow/ adotado a fim de aprimorar a
reprodutibilidade dos resultados aqui apresentados.

#+latex: \noindent
*Configuração do Ambiente de Testes*: Para a execução da aplicação, utilizamos
as plataformas descritas na [[tab:plataformas][Tabela 1]]. Listamos em cada uma dessas o seu
identificador, o(s) processador(es), a quantidade e níveis de memória /cache/ e
quantidade de memória /RAM/.

#+name: tab:plataformas
#+attr_latex: :float t :placement [!htb] :font \small
#+caption: Configuração das plataformas utilizadas nos experimentos.
|---------+----------------------------------------+---------+--------------------+-------------|
| <l>     | <l>                                    | <l>     | <l>                | <l>         |
| *Nome*  | *CPU*                                  | *Nodos* | *L1/L2/LLC*        | *RAM*       |
|---------+----------------------------------------+---------+--------------------+-------------|
| =draco= | $2 \times 8$ Xeon E5 2640 v2 2.5 GHz   | $7$     | 32KB/256KB/20MB    | 64 GB DDR3  |
| =cei=   | $2 \times 12$ Xeon Silver 4116 2.1 GHz | $8$     | 32KB/1024KB/16.5MB | 93 GB DDR4  |
| =hype=  | $2 \times 10$ Xeon E5 2650 v3 2.3 GHz  | $5$     | 32KB/256KB/25MB    | 128 GB DDR4 |
|---------+----------------------------------------+---------+--------------------+-------------|

** Projeto Experimental

A fim de analisar o impacto dos diferentes /runtimes/ aqui avaliados, definimos
como fatores do projeto experimentar o tamanho da *matriz* e o tamanho do
*bloco*. O tamanho do bloco varia em fatores de $2$ entre $[32, 512]$,
resultando, assim, em cinco níveis, enquanto o tamanho da matriz foi fixado em
$8192$. Essa variedade de combinações foi o suficiente para que nós
observássemos acuradamente o impacto do número das tarefas geradas pela a
aplicação. Cada combinação foi repetida 5 vezes para cada experimento em cada
nó para a avaliação do /makespan/ e 1 vez para a coleta do traço das execuções.

** Manipulação de dados com ferramentas modernas de /data science/

A manipulação e análise de dados foi realizada utilizando a linguagem de
programação =R= em conjunto com o pacote de bibliotecas =tidyverse= através de
blocos de códigos embutidos em arquivos =org=. Tal abordagem nos permitiu
alcançar fácil reprodutibilidade e posterior verificação dos resultados obtidos,
além de uma plataforma robusta para a posterior visualização desses resultados.

#+begin_comment
Estou cansado já, mas essa parte precisa de uma séria atenção.
#+end_comment

* Resultados Experimentais e Observações

** Configuração Experimental

#+begin_comment
\noindent
*Configuração Experimental*:
- Configuração de SW e HW
  - Detalhamentos precisos (versão, cores, modelo da CPU, Qtdade memória)
- SW
  - Starpu/LWS
#+end_comment

** Comparação do Escalonamento entre os três /runtimes/

#+begin_comment
Figura que a gente conversou
- cowplot -> ~plot_grid~, alinhamento do eixo X (tempo), eixo Y são os workers
- Selecionar alguns dgeqrt (primeira tarefa de cada laço mais externo)
  - Colocar elas em evidência de maneira sincronizado
#+end_comment

** Análise de Ociosidade por /Worker/

** Diferenças de tempo de execução dos /kernels/ em função do /runtime/

* Conclusão e Trabalhos Futuros

* Referências                                                        :ignore:

# See next section to understand how refs.bib file is created.

#+latex: \bibliographystyle{sbc}
#+latex: \bibliography{refs}

* Miscs                                                            :noexport:
** Bib file                                                       :noexport:

Tangle this file with C-c C-v t

#+begin_src bibtex :tangle refs.bib
% Only BIBTEX entries here

@inproceedings{yoo2003slurm,
 author = {Yoo, Andy B. and Jette, Morris A. and Grondona, Mark},
 title = {SLURM: Simple Linux Utility for Resource Management},
 booktitle = {Job Scheduling Strategies for Parallel Processing},
 year = {2003},
 publisher = {Springer Berlin Heidelberg},
 address = {Berlin, Heidelberg},
 pages = {44--60},
 isbn = {978-3-540-39727-4}
}

@inproceedings{broquedis2012libkomp,
 author = {Broquedis, Fran{\c{c}}ois and Gautier, Thierry and Danjean, Vincent},
 editor = {Chapman, Barbara M. and Massaioli, Federico and M{\"u}ller, Matthias S. and Rorro, Marco},
 title = {libKOMP, an Efficient OpenMP Runtime System for Both Fork-Join and Data Flow Paradigms},
 booktitle = {OpenMP in a Heterogeneous World},
 year = {2012},
 publisher = {Springer Berlin Heidelberg},
 address = {Berlin, Heidelberg},
 pages = {102--115},
 isbn = {978-3-642-30961-8}
}

@inproceedings{nesi2019pcad,
 author = {Lucas Leandro Nesi and Matheus S. Serpa and Lucas Mello Schnorr and Philippe Olivier Alexandre Navaux},
 title = {HPC Resources Management Infraestruture Description and 10-month Statistics},
 booktitle = {Anais do XVII Workshop de Processamento Paralelo e Distribuído},
 location = {Porto Alegre},
 year = {2019},
 keywords = {},
 pages = {21--24},
 url = {https://www.inf.ufrgs.br/gppd/wsppd/2019/papers/proceedings/WSPPDProceedings.pdf}
}

@inproceedings{miletto2019abrest,
 author = {Marcelo Miletto and Lucas Schnorr},
 title = {OpenMP and StarPU Abreast: the Impact of Runtime in Task-Based Block QR Factorization Performance},
 booktitle = {Anais do XX Simpósio em Sistemas Computacionais de Alto Desempenho},
 location = {Campo Grande},
 year = {2019},
 keywords = {},
 pages = {25--36},
 publisher = {SBC},
 address = {Porto Alegre, RS, Brasil},
 doi = {10.5753/wscad.2019.8654},
 url = {https://sol.sbc.org.br/index.php/wscad/article/view/8654}
}

@article{pinto2018ccpe,
 author = {Garcia Pinto, Vinícius and Mello Schnorr, Lucas and Stanisic, Luka and Legrand, Arnaud and Thibault, Samuel and Danjean, Vincent},
 title = {A visual performance analysis framework for task-based parallel applications running on hybrid clusters},
 journal = {Concurrency and Computation: Practice and Experience},
 volume = {30},
 number = {18},
 pages = {e4472},
 keywords = {Cholesky, heterogeneous platforms, high-performance computing, task-based applications, trace visualization},
 doi = {10.1002/cpe.4472},
 url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/cpe.4472},
 eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/cpe.4472},
 note = {e4472 cpe.4472},
 year = {2018}
}

@article{augonnet2011starpu,
 author = {Augonnet, Cédric and Thibault, Samuel and Namyst, Raymond and Wacrenier, Pierre-André},
 title = {StarPU: a unified platform for task scheduling on heterogeneous multicore architectures},
 journal = {Concurrency and Computation: Practice and Experience},
 volume = {23},
 number = {2},
 pages = {187-198},
 keywords = {GPU, multicore, accelerator, scheduling, runtime system},
 doi = {10.1002/cpe.1631},
 url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/cpe.1631},
 eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/cpe.1631},
 year = {2011}
}

@article{stanisic2015workflow,
 author = {Stanisic, Luka and Legrand, Arnaud and Danjean, Vincent},
 title = {An Effective Git And Org-Mode Based Workflow For Reproducible Research},
 journal = {SIGOPS Oper. Syst. Rev.},
 issue_date = {January 2015},
 volume = {49},
 number = {1},
 month = jan,
 year = {2015},
 issn = {0163-5980},
 pages = {61--70},
 numpages = {10},
 url = {http://doi.acm.org/10.1145/2723872.2723881},
 doi = {10.1145/2723872.2723881},
 acmid = {2723881},
 publisher = {ACM},
 address = {New York, NY, USA},
}

@article{knuth1984literate,
 author = {Knuth, D. E.},
 doi = {10.1093/comjnl/27.2.97},
 issn = {0010-4620},
 journal = {The Computer Journal},
 month = 2,
 number = 2,
 pages = {97--111},
 publisher = {Oxford University Press},
 title = {{Literate Programming}},
 volume = 27,
 year = 1984
}

@book{dominik2010orgmode,
 author = {Dominik, Carsten},
 title = {The Org Mode 7 Reference Manual - Organize Your Life with GNU Emacs},
 year = {2010},
 isbn = {1906966087, 9781906966089},
 publisher = {Network Theory Ltd.},
}

@book{stallman2017emacs,
 address = {Boston, USA},
 author = {Richard Stallman and others},
 edition = 17,
 pages = 635,
 publisher = {Free Software Foundation},
 title = {{GNU Emacs Manual}},
 url = {https://www.gnu.org/software/emacs/manual/pdf/emacs.pdf},
 urldate = {2017-12-04},
 year = 2017
}

@manual{rteam2018manual,
 title = {R: A Language and Environment for Statistical Computing},
 author = {{R Core Team}},
 organization = {R Foundation for Statistical Computing},
 address = {Vienna, Austria},
 year = {2018},
 url = {https://www.R-project.org/},
}

@inproceedings{gamblin2015spack,
 title = {The Spack package manager: Bringing order to HPC software chaos},
 author = {Gamblin, Todd and LeGendre, Matthew and Collette, Michael R and Lee, Gregory L and Moody, Adam and de Supinski, Bronis R and Futral, Scott},
 booktitle = {High Performance Computing, Networking, Storage and Analysis, 2015 SC-International Conference for},
 pages = {1--12},
 year = {2015},
 organization = {IEEE}
}
#+end_src

** Emacs setup                                                    :noexport:
# Local Variables:
# eval: (add-to-list 'load-path ".")
# eval: (require 'ox-extra)
# eval: (require 'org-inlinetask)
# eval: (ox-extras-activate '(ignore-headlines))
# End:
